from icecream import ic
# Method Insert()
print('*** Метод insert() ***')
print()
names = ['Gregory', 'Gvido', 'Nikole']
names.insert(1, 'Georgiy')
if 'Anders' in names:
    position = names.index('Anders')
    print(position)
else:
    print('Такого значения нет в списке')
print()
# Method Remove()
print('*** Метод remove() ***')
print()
food = ['Рис', 'Рыба', 'Курица', 'Брокколи', 'Рис']
print(food)
food.remove('Рис')
print(food)
comment1 = 'Метод Remove() удаляет только первый жлемент с указанным значением'
print(comment1)
print()
# Method pop()
print('*** Метод pop() ***')
print()
print(names)
item = names.pop(2)
print('Удален:', item)
print(names)
print()
# Method count()
print('*** Метод count() ***')
print()
names.append('Gregory')
print(names)
cnt1 = names.count('Gregory')
cnt2 = names.count('Georgiy')
cnt3 = names.count('Josef')
print(cnt1)
print(cnt2)
print(cnt3)
print()
# Method reverse()
print('*** Метод reverse() ***')
print()
print(names)
names.reverse()
print(names)
print()
# Method clear()
print('Список до применения Clear()')
print(names)
names.clear()
print('Список после применения Clear()')
print(names)
print()
# Method copy()
print('*** Метод copy() ***')
print('Метод содает копию списка')
food_copy = food.copy()
print(food)
print(food_copy)
