# first = input()
# second = input()
# third = input()
# print(third, second,first, sep='\n')
separator = input("Введи разделитель - ")
end_of_line = input("Введи 'конец строки' - ")
print(end_of_line)
print('a', 'b', 'c', sep=separator)
print('d', 'e', 'f', sep='**', end=end_of_line)
print('g', 'h', 'i', sep='+', end='%')
print('j', 'k', 'l', sep='-', end='\n')
print('m', 'n', 'o', sep='/', end='!')
print('p', 'q', 'r', sep='1', end='%')
print('s', 't', 'u', sep='&', end='\n')
print('v', 'w', 'x', sep='%')
print('y', 'z', sep='/', end='!')